### PR TITLE
Tuto

### PR DESCRIPTION
**Pull request by tboquet**
Added Keras tutorial.

---

This change is [Reviewable](https://reviewable.io/reviews/tboquet/python-alp/17)

### CODE REVIEW

**Comment by DrAnaximandre** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[docs/dockersetup.rst, line 63 [r1]](https://reviewable.io:443/reviews/tboquet/python-alp/17#-KJfOWHIvXa-rgeXWPVC:-KJfOWHIvXa-rgeXWPVD:1976840152) ([raw file](https://github.com/tboquet/python-alp/blob/38144de9527354dd0abc27d7a79e00f18b3c8897/docs/dockersetup.rst#L63)):_

> ``` reStructuredText
> The architecture could be resumed as:
> 
> .. image:: _static/architecture.svg
> ```

Change the image ? Since the controller has access to Mongo.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/17)_

**Comment by tboquet** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[docs/dockersetup.rst, line 63 [r1]](https://reviewable.io:443/reviews/tboquet/python-alp/17#-KJfOWHIvXa-rgeXWPVC:-KJfPBqMHRHHo2yt-38U:-499146009) ([raw file](https://github.com/tboquet/python-alp/blob/38144de9527354dd0abc27d7a79e00f18b3c8897/docs/dockersetup.rst#L63)):_
<details><summary>

<i>Previously, DrAnaximandre wrote…</i></summary>



> Change the image ? Since the controller has access to Mongo.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/17)_

**Comment by DrAnaximandre** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[docs/dockersetup.rst, line 63 [r1]](https://reviewable.io:443/reviews/tboquet/python-alp/17#-KJfOWHIvXa-rgeXWPVC:-KJfPFbLpXOg7QsrTpGI:676834233) ([raw file](https://github.com/tboquet/python-alp/blob/38144de9527354dd0abc27d7a79e00f18b3c8897/docs/dockersetup.rst#L63)):_
<details><summary>

<i>Previously, tboquet (Thomas Boquet) wrote…</i></summary>



> Done.
> </details>
> LGTM

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/17)_

**Comment by DrAnaximandre** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/17)_

**Comment by DrAnaximandre** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/17)_

**Pull request merged**
