### PR TITLE
User defined op for ensembles

### PR DESCRIPTION
**Pull request by tboquet**
- [x] change the behavior of predict and summary to be able to accept user defined metrics
- [x] test sklearn models in ensembles

---
This change is [Reviewable](https://reviewable.io/reviews/tboquet/python-alp/75)

### CODE REVIEW

**Comment by DrAnaximandre** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/alp/appcom/ensembles.py, line 76 at r2](https://reviewable.io:443/reviews/tboquet/python-alp/75#-KZcQdcUVwmvMgTp39mJ:-KZcQdcUVwmvMgTp39mK:b-y0g1s9) ([raw file](https://github.com/tboquet/python-alp/blob/e108d543238e1978406eb8f65779dfea06cf9bd5/src/alp/appcom/ensembles.py#L76)):*
> ```Python
>         hyperparams(dict): a dict of hyperparameters
>         metric(str): the name of a metric used in the experiments
>         op(str): an operator to select a model
> ```

put an example of op in the docstring?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/75)*

**Comment by tboquet** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/alp/appcom/ensembles.py, line 76 at r2](https://reviewable.io:443/reviews/tboquet/python-alp/75#-KZcQdcUVwmvMgTp39mJ:-KZgQ_sAtTY1ibwcth54:b-896fix) ([raw file](https://github.com/tboquet/python-alp/blob/e108d543238e1978406eb8f65779dfea06cf9bd5/src/alp/appcom/ensembles.py#L76)):*
<details><summary><i>Previously, DrAnaximandre wrote…</i></summary><blockquote>

put an example of op in the docstring?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/75)*

**Comment by DrAnaximandre** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/75#-:-KZgTljR-Edndgql37OQ:bnfp4nl)*

**Comment by DrAnaximandre** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/75)*

**Pull request merged**
