### PR TITLE
[WIP] Serialized generators db

### LINKED ISSUE #37: Serialization of the generator
We should also serialize and save the generators in the db to be able to reload them for prediction.

### PR DESCRIPTION
**Pull request by tboquet**
(closes #37 )
To be able to reuse the same generator, this PR brings a new collection in the database.
- [x] core functionalities
- [x] tests

---

This change is [Reviewable](https://reviewable.io/reviews/tboquet/python-alp/38)

### CODE REVIEW

**Comment by tboquet** [comment]
@DrAnaximandre could you review these first changes please :birthday: ?

**Comment by DrAnaximandre** [comment]
here is what i get from the review.
- there are now two collections:  models and generators
- tensorflow is supported in the tests
- todo for me : another PR for the support of generators in scikit

---

Reviewed 2 of 6 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/alp/backend/sklearn_backend.py, line 322 at r2](https://reviewable.io:443/reviews/tboquet/python-alp/38#-KUwsL9p27XeuKA_7sxG:-KUwsL9p27XeuKA_7sxH:ba01r6l) ([raw file](https://github.com/tboquet/python-alp/blob/a733c13242a2250597e76e646d1148ebb31dc9ba/src/alp/backend/sklearn_backend.py#L322)):_

> ``` Python
>     mod_id = db.insert(full_json, db.get_models(), upsert=overwrite)
> 
>     if generator is True:  # pragma: no cover
> ```

will do that case

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/38#-:-KUwt0k6TcJbOGSmj6vx:b1wcrku)_

**Comment by tboquet** [comment]
@dranaximandre I removed the other objective since we could merge this first part and open another PR to support custom Fuel elements. Could you review the new changes? tx!

---

Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/alp/backend/sklearn_backend.py, line 322 at r2](https://reviewable.io:443/reviews/tboquet/python-alp/38#-KUwsL9p27XeuKA_7sxG:-KV21aPZIxn-5FFYH32C:b4putsz) ([raw file](https://github.com/tboquet/python-alp/blob/a733c13242a2250597e76e646d1148ebb31dc9ba/src/alp/backend/sklearn_backend.py#L322)):_
<details><summary>

<i>Previously, DrAnaximandre wrote…</i></summary>



> will do that case
> </details>
> :ok_hand: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/38#-:-KV211B5dRsCcYofxubd:bb1q2xg)_

**Comment by DrAnaximandre** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/38#-:-KVAAyxduC_fz0LcnCH5:bnfp4nl)_

**Pull request merged**
