### PR TITLE
Issue55

### PR DESCRIPTION
**Pull request by DrAnaximandre**
fixes first part of #55

---
This change is [Reviewable](https://reviewable.io/reviews/tboquet/python-alp/65)

### CODE REVIEW

**Comment by DrAnaximandre** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/alp/backend/sklearn_backend.py, line 291 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr0KnmyyE_l7yhpqwZ:-KXr0KnmyyE_l7yhpqw_:b-7itwit) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L291)):*
> ```Python
>         custom_objects = kwargs.pop('custom_objects')
> 
>     # vestigial code to be rm after validation
> ```

to rm

---

*[src/alp/backend/sklearn_backend.py, line 382 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr15y9JaL4yxDVwSpc:-KXr15y9JaL4yxDVwSpd:b-aiutcz) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L382)):*
> ```Python
>             else:
>                 for metric in metrics_names:
>                     if metric is not 'score':
> ```

refactor loop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/65)*

**Comment by DrAnaximandre** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/alp/backend/sklearn_backend.py, line 291 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr0KnmyyE_l7yhpqwZ:-KXr2upOIUNp7CKTdKXM:b-896fix) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L291)):*
<details><summary><i>Previously, DrAnaximandre wrote…</i></summary><blockquote>

to rm
</blockquote></details>

Done.

---

*[src/alp/backend/sklearn_backend.py, line 382 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr15y9JaL4yxDVwSpc:-KXr32oMNX1L8s8uZhKD:b-896fix) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L382)):*
<details><summary><i>Previously, DrAnaximandre wrote…</i></summary><blockquote>

refactor loop
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/65)*

**Comment by tboquet** [comment]
LGTM

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/65#-:-KXrWRhd8PUd2sz3l_Hi:bb6ywmx)*

**Comment by tboquet** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/alp/backend/sklearn_backend.py, line 291 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr0KnmyyE_l7yhpqwZ:-KXrWc2Prx78Zg2bPA3H:b32w0x) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L291)):*
<details><summary><i>Previously, DrAnaximandre wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/65)*

**Comment by tboquet** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/alp/backend/sklearn_backend.py, line 382 at r8](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXr15y9JaL4yxDVwSpc:-KXrWiEXWTNdLEoycWLq:b32w0x) ([raw file](https://github.com/tboquet/python-alp/blob/08ac304395258404267686a2d43a04800cba08f7/src/alp/backend/sklearn_backend.py#L382)):*
<details><summary><i>Previously, DrAnaximandre wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---

*[tests/backend/test_sklearn_backend.py, line 219 at r9](https://reviewable.io:443/reviews/tboquet/python-alp/65#-KXpvHTU6uXPuGXQt8qq-r9-219:-KXrWkziF3dvmUtbm5U_:b32w0x) ([raw file](https://github.com/tboquet/python-alp/blob/948afe583d50e5fddd48fc58d0702fbdfd673560/tests/backend/test_sklearn_backend.py#L219)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary><blockquote>

Codacy Issue found: [Unused variable 'model'](https://www.codacy.com/app/thomas-boquet/python-alp/file/4605103514/issues/source?bid=3232749&fileBranchId=3953153#l219)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tboquet/python-alp/65)*

**Pull request merged**
